kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: ""
layouts_dir: "layout"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor", "layout"]

repository: amphp/amphp.github.io
gems:
 - "jekyll-redirect-from"
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

shared_asset_path: ""
