kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/"
layouts_dir: ".shared/layout"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
include: [".shared"]

repository: amphp/amphp.github.io
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

asset_path: "/.shared/asset"
